# Generated by Django 3.2.13 on 2022-05-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id'], 'verbose_name': 'subscribe', 'verbose_name_plural': 'Управление подписками'},
        ),
    ]
